
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/dglavinkov/ondemand/zeogen/source/main.py", line 7, in <module>
    import torch
  File "/gpfs/home5/dglavinkov/ondemand/thesis/lib/python3.11/site-packages/torch/__init__.py", line 1471, in <module>
    from .functional import *  # noqa: F403
  File "/gpfs/home5/dglavinkov/ondemand/thesis/lib/python3.11/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/gpfs/home5/dglavinkov/ondemand/thesis/lib/python3.11/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/gpfs/home5/dglavinkov/ondemand/thesis/lib/python3.11/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/gpfs/home5/dglavinkov/ondemand/thesis/lib/python3.11/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/gpfs/home5/dglavinkov/ondemand/thesis/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
Traceback (most recent call last):
  File "/home/dglavinkov/ondemand/zeogen/source/main.py", line 15, in <module>
    from diffusion_model import DiffusionModel
  File "/gpfs/home5/dglavinkov/ondemand/zeogen/source/diffusion_model.py", line 20, in <module>
    from data_utils.crystal_utils import frac_to_cart_coords, cart_to_frac_coords, min_distance_sqr_pbc, mard, lengths_angles_to_volume
  File "/gpfs/home5/dglavinkov/ondemand/zeogen/source/data_utils/__init__.py", line 1, in <module>
    from .crystal_utils import save_samples_as_cifs, save_reconstructions_as_cifs, visualize_trajectory
  File "/gpfs/home5/dglavinkov/ondemand/zeogen/source/data_utils/crystal_utils.py", line 6, in <module>
    from pymatgen.core.structure import Structure
ModuleNotFoundError: No module named 'pymatgen'

JOB STATISTICS
==============
Job ID: 7937797
Cluster: snellius
User/Group: dglavinkov/dglavinkov
State: RUNNING
Nodes: 1
Cores per node: 9
CPU Utilized: 00:00:00
CPU Efficiency: 0.00% of 00:02:33 core-walltime
Job Wall-clock time: 00:00:17
Memory Utilized: 0.00 MB (estimated maximum)
Memory Efficiency: 0.00% of 60.00 GB (60.00 GB/node)
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
